spring:
  application:
    name: library

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${AUTH_HOSTNAME}:${AUTH_PORT}/oauth2/jwks

  datasource:
    url: jdbc:mysql://${MYSQL_HOSTNAME}:${MYSQL_PORT}/library_data
    username: admin
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

library:
  presence:
    elementsOnPage: 25

#server:
#  ssl:
#    key-store-type: PKCS12
#    key-store: classpath:library_cert.p12
#    key-store-password: secret
#    key-alias: library_cert
#    enabled: true
